### ISSUE TITLE
Receipt Generation from Payment

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#11]
Based on something like this:  https://docs.google.com/document/d/1qYX9y39OyC7ROpRdae4SYUaRdRBiC_akeSpDlamIBfw/edit

**Comment by billyc** [comment]
membership@z.. and the user will will now get a very brief email confirmation with the user name, email, membership type, and amount charged.  I won't have time today to generate a full receipt, but I can add that this weekend, I think.

NOTE: -- the email is going to come from sfbilly@g... until @e-lo and I chat, because the membership@z.. account needs a "app-specific password" set up in order for me to send email from Heroku through that account.  see https://support.google.com/accounts/answer/185833?hl=en to set it up

**Comment by billyc** [comment]
(note everything is still in "test" mode -- nothing is actually live yet

**Comment by billyc** [comment]
Upon successful Stripe payment, email now being sent to zephyr and to the end user. It's not a fancy receipt but it will do for now I hope!
