### ISSUE TITLE
Add complementary membership tier

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#23]
For founding stakeholders.
Should still allows them to donate...and makes them click-accept the terms of membership.

**Comment by e-lo** [comment]
[ probably best to be hidden link ]

**Comment by e-lo** [comment]
@billyc  -  LMK if this is something you can get to soon-ish; otherwise I will take a crack at it so that we don't lose too much time/momentum from TRB.

**Comment by billyc** [comment]
I am unclear on exactly what the flow for this is. I think I can set it up
this week. What do we want?

- A hidden page (i.e., simply a non-advertised URL)
- [x] I agree to the thing

...and then what? No Stripe passthrough, because we're not asking for
payment. But you say you want a donation slot available. So... take their
name and email, and after we have those, *forward* them to the donation
page?

Once we're clear on what we want I can do... well, anything.

**Comment by e-lo** [comment]
anything?

**Comment by e-lo** [comment]
Was thinking a single page with the following:

1. Form for I, XXX, agree to abide by and be a member of Zephyr - and here is my email.
2. "...Your membership is complimentary for 2018, but we would really appreciate your donation at any level...see below options to make a donation today" 
3. Donation boxes ranging from approx $50-500

**Comment by billyc** [comment]
That all seems straightforward enough. But I'll have to figure out how to
receive the click from the form, since it isn't going through stripe. So
it'll take me a little time to figure out.

**Comment by e-lo** [comment]
maybe a google form embed?

**Comment by billyc** [comment]
Oh we already have a server running; I'll just add another API endpoint.
But if it goes sideways I'll switch to a Google form :-)

**Comment by billyc** [comment]
Implemented "unadvertised page" -- not really "hidden", per se -- available at 

https://zephyrtransport.org/complimentary-membership

Should work now. @e-lo feel free to edit text on that page, I just ripped out most of the stuff from the regular membership page.

**Comment by e-lo** [comment]
Worked from the user-end.  What gets sent to the admin side?

**Comment by billyc** [comment]
calling this finished
